Catch up to main branch (#1)
* Add transform.chop conformance test

* Add rotozoom conformance test

* implement transform.chop

* Tweak rotozoom output layout

* import pygame's rotozoom implementation

* Add blend mode conformance tests

* fix draw.lines() with all lines clipped

If the set of lines given to draw.lines() are all outside the surface,
it will pass _make_drawn_rect() an empty array and trigger an
exception.

This patch makes it return None instead in this case. See
_clip_and_draw_line_width() for similar code.

* Initial setup.py.

* Rename modules with ffi.cdefs to equivalent build modules.

* Move cffi verify to cffi.set_source builders.

* Ignore generated C files.

* Attempt at building an installable package.

* Remove incorrectly included so file

* Build Mac OS X magic properly.

* Relative imports make puppies cry.

* Limit the package list to pygame only

This avoids installing the examples and test directories as packages.

* Add missing newline at end of .gitignore.

* Add SDL_INIT_JOYSTICK.

* Add skeleton for joystick module.

* Add SDL joystick functions.

* Implement module-level functions for pygame.joystick.

* Implement pygame.joystick.Joystick.

* Update the README to reflect the packaging

* (Add .eggs/ to .gitignore)

* Add conformance test for smoothscale

* Pull in generic c-only smoothscale implementation

* Force generated smoothscale examples to use GENERIC backend, since SSE backend gives slightly different results

* Implement missing alignment check

* Clarify that we are LGPL-2.1+, based on pygame's copyright

* (fijal, jerith) "fix quoting"

* Add license header to stretch.c

* Add license header to rotate.c

* Update FSF address in c files

* Update FSF address in .py files

* Add license header to smoothscale

* fix os x on pypy

* Add a script for doing in-place builds (for development)

* Describe local dev

* Ignore the .m that gets generated in CFFI building

* Document running tests

* This is supposed to be markdown

* Rename tests to demos

* That's a command

* Remove global *.c ignore, since cffi build stuff has change

* Make 'lib' excludes less aggressive, since we have stuff under cffi_builders/lib we care about

* Release to PyPI

Accidentally screwed up 0.0.1, and versions aren't re-useable.

* Import bitmask stuff from pygame

* Fix FSF address

* Add bitmask to sdl build

* strip out some stuff not needed for the pygme_cffi build

* Expose bitmask functions

* Ignore the .c files cffi_builders/build.py creates

* Skeleton mask module

* Arguments can't be implicitly unpacked in Python 3

* Fairly sure that's a mistake in cc8b61f7

You didn't mean to use the buffer builtin there.
Going from the C implementation, the expected thing to do here is limit
the chunk size.

* Add iteritems to pygame.compat

* Add string_types to pygame.compat

* hex() calls __index__ in Python 3

* Use floordiv in __floordiv__

* Use xrange_ from pygame.compat

With an integer argument

* More integer division required

* zip returns an iterator in Python 3

* Python 3 checks __bool__ rather than __nonzero__ for boolean tests

* Python 3 compatible byte-string handling for fonts

* Ensure ext is a bytestring

* Extensions will be byte strings

* Add chr_ helper to pygame.compat for building byte arrays

* mode must be a byte string

* Colors are integers

* More integer division

* Bytes aren't string types, in Python 3

* Simpler one-entry dict unpacking

* Use unicode_ from compat

* File objects are all subclasses of IOBase

* Look at the value not the name

* Perform integer division

* Claim Python 3 support

* Python3 compatible print

* Encode titles and icons to byte strings

* Point out where we ignore upstream's sensibilities

* Avoid a wrapper function under Python 2

* get_pitch should return the pitch

* Pull out as_unicode and as_bytes

We don't support Python 2.6 or 3.2, any more.

* Explain that chain of functions

* Maybe we don't need iteritems(), none of this is performance-sensitive

* Some implementation that seems to match pygame well enough for now

* Add something of a pygame.mask test suite

* Add fill and clear

* Mark all expected test failures (due to incomplete pygame compatibilitiy)

* Add missed bitmask function

* More mask methods

* Replace passes with NotImplementedError, as being more correct

* Implement centroid

* Add Mask to toplevel pygame namespace

* pygame has test for mask, so lets use them

Our tests cover a bunch of different things that the pygame tests don't,
so we keep them as well.

* Implement mask.angle. Fix some bugs

* TTF_STYLE_STRIKETHROUGH isn't available in Ubuntu 12.04, which Travis uses

* Grab cc_label from pygame's mask.c

* Detect xvfb in font_test, its screen seems to be weird

* Fix calls to bitmask_threshold

* Python 3.5 doesn't have subprocess.mswindows any more

* Attempt at a Travis CI config

* Travis CI has numpy

* Some shields

* More stuff from mask.c

* Allow bypassing expected_failure and expected_error

* Document --expected-failures

* Add mask.get_bounding_rects. Fix some other bugs

* Fix overlap method signature

* Pull assertMaskEquals across from pygame

* Hook up erase and draw

* Free bitmask memory, since that turns out to be a good idea

* More stuff from mask.c

* Add connected component methods

* Add tests for overlap_area and overlap_mask

* Implement overlap methods

* PEP8

* Implement outline

* Extend mask outline tests

* We shouldn't return in the success case in the expected_error and expected_failure helpers, so we can detect unexpected successes

* Implement loading from buffer

* Implement _samples_address

* Remove expected_error flag

* Fix logic around byte strings as paths in python 3

* Latest SDL gives a different message for soundfont failure

* Correctly handle set_error and get_error in python 3

* Remove incorrect unexpected_failures

* Skip some unneeded copies

* Test more of the buffer loading code

* Implement ellipse and circle draw functions

* Add ellipse and circle conformance tests

* Add bounds checking to ellipse _set_at calls

* Fix bug in ellipse drawing

* Fix print usage so conformance tests can run under python 3

* Remove misleading copy-n-paste comment

* Fix typo

* Split up buffer loading tests

* Return a Python string for the joystick name (not cdata).

* Fix line order merge mistake.

* Fix cleaning up of open joysticks.

* Fix open joystick freeing again (dicts aren't lists, doh).

* Remove debugging loop exit

* Fix comment

* Add classmethod to create a mask from a c bitmask object

* Add explanatory comment about return values

* Bump version number for release

* Add an AUTHORS file, since it's mentioned in MANIFEST.in

* Fix set_timer test

* Fix call to ffi.new in _timer_callback

* Cleanup timer events of exit, to ensure sane shutdown behaviour

* Add comment to discuss why our handling of the allocated event is safe

* PEP-8 fixes, since I'm working here anyway

* Silently drop blocked events, rather than raising an exception

* Be less restrictive about what's acceptable for music.set_endevent, to match pygame

* Correct check is if video is initialised before trying to use SDL_PushEvent (see note in event.py, pygame's src/mixer.c and SDL docs)

* I accidently fixed a test, so remove the expected_error

* Add mention of pygame's behaviour

* Need a lot more detail from SDL_RWops

* Add support for wrapping non-file objects for image load

* No filename info is not a fatal condition here

* More tests pass

* Add load from BytesIO test case

* Python 3 throws a different error, so catch that one as well

* Small cleanups

* Enable some filelike object tests. Add some tests around endevent handling

* Fix behaviour of unsetting music endevent to match pygame's

* We need to convert the SDL keysym value into an actual unicode character, rather than just claiming to do so

* Add a global set to hold references to the handles we create. Need to fix a bug exposed by later cffi versions

* Actually raising ValueError for incorrect input would be a good idea

* These errors should be raised as well

* Color should accept long values and input, and treat it the same as the int case

* The comments lie.

The long/int tests only do what they claims to do on 32-bit
platforms, which is less than ideal, so we add explicit
casts to test the behaviour we actually trying to test.

* Should also handle longs in calls to create_color

* More compact inistance checks

* We have an irc channel

* ctypes.pythonapi isn't defined on pypy, so don't require it for testing.

We don't currently implement pygame's array interface, so the testing
helpers in test/test_utils/arrinter.py aren't currently useful.
However, they are unconditionaly imported, which causes a bunch
of spurious failures when running the test suite on pypy, due
to arrintr.py throwing NameError because of the non-existant module.

This avoids those failure by ensuring we create stub functions for
this case. If we ever implement the array interface, these helpers
will need to be complete rewritten.

* Add logic so we can test pypy using the version from the launchpad ppa

* Keep a copy of all buffer objects used to create sounds, to match recent pygame behaviour

* Remove PyBytes_FromString test.

This test is meaningless on PyPy, and also doesn't test what it
aims to test on CPython, since PyBytes_FromString returns
the address of the PyObject, not the string buffer we're
actually interested in.

* Bump version number

* Pygame converts dest argument to int before passing it to SDL. We should do likewise

* Implement Rect.__new__

* Add comment

* Add subclassing rect test case, on general principles.

* Update cffi minimum version

* Mention cffi version in README

* Added dummy versions of Surface.lock() and Surface.unlock().

This will allow Pygame code that uses these functions to work, if
more slowly.

* Fix crash in smoothscale

As reported on irc.

Smoothscale handled the non-transform case incorrectly when the
pitch of the destination surface was not the same as the the original
surface (which happens when dealing with subsurfaces as the source,
for example). This changes the logic to copy the image a row at a
time to avoid that issue (which matches pygame's logic).

* Add subsurface + smoothscale test case

* Clarify comment

* Fix copy-and-paste docstring error

* chop and flip should also not assume that the source surface pitch == destination surface pitch

* Add subsurface tests to other transforms

* Fix pitch / type size errors

* Include fonts and images from the pygame package in builds.

* Split subsurface tests out into their own test cases

* Expose THECOLORS to color.py

Expose THECOLORS to color.py, since some games use pygame.color.THECOLORS and pygame exposes THECOLORS in the same way:
pygame_cffi:
>>> pygame.color.THECOLORS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'THECOLORS'

pygame:
>>> import pygame
>>> pygame.color.THECOLORS
{'maroon4': (139, 28, 98, 255), 'gold': (255, 215, 0, 255), 'dodgerblue3': (24, 116...long list of colors)

* Change inline to INLINE (defined in bitmask.h)

bitmask.h have INLINE def, which is needed for bitmask.c to build pygame-cffi on Windows